### ISSUE TITLE
Does not work with ES6 'import'

### ISSUE THREAD

**Issue by v-honcharenko** [abbotto/teleprint#1]
It is impossible to import teleprint with 'es6 import' and webpack.
Please, add the **[main](https://docs.npmjs.com/files/package.json#main)** field to package.json

**Comment by abbotto** [comment]
@HackedBeat 

Thanks for pointing this out.
I've added the entry point to "package.json" and bumped the version to v2.0.4.

**Comment by gerwinbrunner** [comment]
I'm not sure that this is working...
When I try to do the import like 
```
import teleprint from 'teleprint';
```
The teleprint variable keeps being undefined, but I do not get any error :(
Any idea what the problem could be?

**Comment by abbotto** [comment]
@gerwinbrunner 

In this case, `teleprint` will be attached to the `window` object.

```
import teleprint from "teleprint";
const teleprint = window.teleprint;
```

[Link to example](https://codepen.io/abbotto/project/editor/DGgqQM)
