### ISSUE TITLE
Do not works with Electron?

### ISSUE THREAD

**Issue by ghost** [abbotto/teleprint#3]
Hi.

I'm trying to use teleprint with an HTML page in Electron (v.5.0.6) without success...
I'm declaring with `<script>let teleprint = required('teleprint');</script>`, but on call I'm receiving the error "teleprint is not defined".

May you help me with this, please?

Thank you so much.
Regards.

**Comment by ghost** [comment]
My falt.... My correct declaration is `<script>let teleprint = require('teleprint');</script>`

**Comment by abbotto** [comment]
Thanks for using Teleprint.
